# 全局配置
server:
  servlet:
    context-path: /idserver
  port: 8086
# spring 配置
spring:
  profiles: # 多环境配置
    active: dev
  mvc: # 404 异常处理
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  devtools: # 热部署
    restart:
      enabled: true
      exclude: application.yml
  application: 
    name: service-id-generator
# 日志管理
# Spring Boot中默认配置了ERROR、WARN和INFO级别的日志输出到控制台。
#debug: true
# 文件输出
logging:
  config: classpath:log/logback.xml
# 文件上传配置
multipart:
  maxFileSize: 50Mb # 最大支持文件大小 即单个文件大小
  maxRequestSize: 50Mb  # 最大支持请求大小 即一次性上传的总文件大小
eureka: # eureka client config
  client:
    # 是否启用eureka客户端。默认true
    enabled: false # 本地调试时，若不想启动eureka，可配置false
    serviceUrl: 
      defaultZone: http://localhost:9090/eureka/ # eureka服务的位置，如果需要注册多个服务器，可用逗号隔开
  instance: 
    preferIpAddress: false # 默认false, 是否以IP注册到Eureka Server上
    instanceId: ${spring.application.name}
    # 端点配置。若配置了context-path，actuator的监控端点会增加前缀，此时eureka也需要相应增加
    status-page-url-path: ${server.servlet.context-path}/info
    health-check-url-path: ${server.servlet.context-path}/health