# 全局配置
server:
  servlet:
    context-path: /file
  port: 8085
# spring 配置
spring:
  profiles: # 多环境配置
    active: local
  mvc: # 404 异常处理
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  devtools: # 热部署
    restart:
      enabled: true
      exclude: application.yml
  application: 
    name: file-server
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/c_system?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    dbcp2:
      validation-query: select 1
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true

# 日志管理
# Spring Boot中默认配置了ERROR、WARN和INFO级别的日志输出到控制台。
#debug: true
# 文件输出
logging:
  config: classpath:logback.xml
# api日志管理
apiLog:
  tableName: apilog
  daysToKeep: 1
  datasource:
    driverClass: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/c_system?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    user: root
    password: root

# 文件上传配置
multipart:
  maxFileSize: 50Mb # 最大支持文件大小 即单个文件大小
  maxRequestSize: 50Mb  # 最大支持请求大小 即一次性上传的总文件大小

# eureka client config
eureka: 
  client:
    # 是否启用eureka客户端。默认true
    enabled: false # 本地调试时，若不想启动eureka，可配置false
    serviceUrl: 
      defaultZone: http://localhost:9090/eureka/ # eureka服务的位置，如果需要注册多个服务器，可用逗号隔开
  instance: 
    preferIpAddress: false # 默认false, 是否以IP注册到Eureka Server上
    instanceId: ${spring.application.name}
    # 端点配置。若配置了context-path，actuator的监控端点会增加前缀，此时eureka也需要相应增加
    status-page-url-path: ${server.servlet.context-path}/info
    health-check-url-path: ${server.servlet.context-path}/health

# 分布式ID——雪花算法
snowflake:
  datacenterId: 1
  machineId: 1

# 文件服务配置
file-service:
  windows:
    storageDir: ${user.dir}/temp/file-server/
    mdUrlPattern: /md/**
    mdDiskDir: D:/Workspaces/individual-study/guide-manual/
  linux:
    storageDir: ${user.dir}/temp/file-server/
    mdUrlPattern: /md/**
    mdDiskDir: /home/guanyw/workspaces/individual-study/guide-manual/