server:
  port: 8082

spring:
  profiles:
    active: default
  #热部署
  devtools:
    restart:
      enabled: true

# 爬虫库资源
crawler:
  ds:
    host: localhost
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://%s:3306/db_crawler?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    userName: root
    password: root
  csv:
    fileDir: /root/data

local:
  file: /root/config-center/local.properties