server:
  port: 8082

# 爬虫库资源
crawler:
  ds:
    host: localhost
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://%s:3306/db_crawler?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    userName: root
    password: root
  csv:
    fileDir: D:/ftx_new_house_20211108.csv

local:
  file: /config-center/local.properties