server:
  port: 8089

# 文件输出
logging:
  config: classpath:log/logback.xml

# Mybatis config
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:cn/gyw/**/mapper/*.xml

es:
  host: 127.0.0.1
  port: 9200
  schema: http