# server 
server:
  port: 9090

# eureka
eureka:
  server:
    # 是否开启自我保护模式，默认为true
    enable-self-preservation: true
    # 续期时间，即扫描失效服务的间隔时间
    eviction-interval-timer-in-ms: 10000
  client:
    # 设置是否将自己作为客户端注册到注册中心（缺省true）
    register-with-eureka: false
    # 设置是否从注册中心获取注册信息，单点的EurekaServer，不需要同步其它EurekaServer节点的数据，故设为false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/