ds:
  system:
    driverClassName: com.mysql.jdbc.Driver
    host: localhost
    url: jdbc:mysql://%s:3306/backend_system?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: backend-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头